#############
### build ###
#############

# base image
FROM node:12.2.0 as build

# install chrome for protractor tests
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -yq google-chrome-stable

# set working directory
WORKDIR /co-etech-training-web

# add `/co-etech-training-web/node_modules/.bin` to $PATH
ENV PATH /co-etech-training-web/node_modules/.bin:$PATH

# install and cache co-etech-training-web dependencies
COPY package.json /var/lib/jenkins/workspace/WebAppCICD/src/dev/resources/package.json
RUN npm install
RUN npm install -g @angular/cli@7.3.9

# add co-etech-training-web
COPY . /co-etech-training-web

# generate build
RUN ng build --output-path=dist

############
### prod ###
############

# base image
FROM nginx:1.16.0-alpine

# copy artifact build from the 'build environment'
COPY --from=build /co-etech-training-web/dist /usr/share/nginx/html

# expose port 80
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]