kind: Template
apiVersion: v1
labels:
  template: webapp-production-deployment
  group: webapp-production-deployment
  application: webapp
  environment: production
metadata:
  annotations:
    description: CoE webapp API Production A/B Deployments
    tags: webapp-production-deployment
  name: webapp-production-deployment
message: CoE webapp Production Deployment Template

objects:
#Application Route
- apiVersion: v1
  kind: Route
  metadata:
    name: "webapp"
  spec:
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect  
    to:
      kind: Service
      name: "a-webapp-opr-svc"
      weight: 50
    alternateBackends:
    - kind: Service
      name: "b-webapp-opr-svc"
      weight: 50

#Application A Deployment
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "a-webapp-opr-dc"
  spec:
    replicas: 1
    selector:
      name: "a-webapp-opr-dc"
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: "a-webapp-opr-dc"
      spec:
        containers:
        - name: "a-webapp"
          image: "a-webapp-is"
          env:
          - name: DATABASE_NAME
            value: -database
          ports:
          - containerPort: 9000
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 90
            timeoutSeconds: 180
            periodSeconds: 90
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: 9000
              initialDelaySeconds: 90
            timeoutSeconds: 180
            periodSeconds: 90
            successThreshold: 1
            failureThreshold: 10
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m             
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "a-webapp"
        from:
          kind: ImageStream
          name: "a-webapp-is:1.0.0"

- kind: HorizontalPodAutoscaler
  apiVersion: autoscaling/v1
  metadata:
    name: a-webapp-opr-hpa
  spec:
    scaleTargetRef:
      kind: DeploymentConfig
      name: a-webapp-opr-dc
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    
#Application Service    
- kind: Service
  apiVersion: v1
  metadata:
    name: "a-webapp-opr-svc"
  spec:
    ports:
    - name: webapp
      port: 9000
      targetPort: 9000
    selector:
      name: "a-webapp-opr-dc"
#Route
- kind: Route
  apiVersion: v1
  metadata:
    name: "a-webapp"
  spec:
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    to:
      kind: Service
      name: "a-webapp-opr-svc"

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "a-webapp-is"
  spec:
    dockerImageRepository: "aceinfocoe"
    importPolicy:
      insecure: true
    name: 1.0.0

- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "b-webapp-is"
  spec:
    dockerImageRepository: "aceinfocoe"
    importPolicy:
      insecure: true
    name: 1.0.0

#Application B Deployment
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "b-webapp-opr-dc"
  spec:
    replicas: 1
    selector:
      name: "b-webapp-opr-dc"
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: "b-webapp-opr-dc"
      spec:
        containers:
        - name: b-webapp
          image: "b-webapp-is"
          env:
          - name: DATABASE_NAME
            value: -database
          ports:
          - containerPort: 9000
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 90
            timeoutSeconds: 180
            periodSeconds: 90
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 90
            timeoutSeconds: 180
            periodSeconds: 90
            successThreshold: 1
            failureThreshold: 10
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "b-webapp"
        from:
          kind: ImageStream
          name: "b-webapp-is:1.0.0"

#Application Service    
- kind: Service
  apiVersion: v1
  metadata:
    name: "b-webapp-opr-svc"
  spec:
    ports:
    - name: web
      port: 9000
      targetPort: 9000
    selector:
      name: "b-webapp-opr-dc"
#Route
- kind: Route
  apiVersion: v1
  metadata:
    name: "b-webapp"
  spec:
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect 
    to:
      kind: Service
      name: "b-webapp-opr-svc"

- kind: HorizontalPodAutoscaler
  apiVersion: autoscaling/v1
  metadata:
    name: b-webapp-opr-hpa
  spec:
    scaleTargetRef:
      kind: DeploymentConfig
      name: b-webapp-opr-dc
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
      