kind: Template
apiVersion: v1
labels:
  template: bdso-webapp-testing-deployment
  group: bdso-webapp-testing-deployment
  application: webapp
  environment: staging
metadata:
  name: bdso-staging-deployment
message: BDSO Staging Deployment of Webapp

objects:
#APPLICATION
- kind: Service
  apiVersion: v1
  metadata:
    name: "webapp-stg-svc"
  spec:
    ports:
    - name: "webapp-stg-svc"
      port: 9000
      targetPort: 9000
    selector:
      name: "webapp-stg-dc"
    sessionAffinity: None

#Application Route
- kind: Route
  apiVersion: v1
  metadata:
    name: webapp
  spec:
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect 
    to:
      kind: Service
      name: "webapp-stg-svc"

# Application ImageStream
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "webapp-is"
  spec:
    dockerImageRepository: "aceinfocoe"
    importPolicy:
      insecure: true
    name: 1.0.0

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "webapp-stg-dc"
  spec:
    replicas: 1
    selector:
      name: "webapp-stg-dc"
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: "webapp-stg-dc"
      spec:
        containers:
        - name: webapp
          image: "webapp-is"
          env:
          - name: DATABASE_NAME
            value: -database
          ports:
          - containerPort: 9000
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 45
            timeoutSeconds: 30
            periodSeconds: 45
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /
              port: 9000
              initialDelaySeconds: 90
            timeoutSeconds: 180
            periodSeconds: 90
            successThreshold: 1
            failureThreshold: 10
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "webapp"
        from:
          kind: ImageStream
          name: "webapp-is:1.0.0"
